# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb39bcdda44675eb53e2b5051fcf45f21f1a3b9cdad8f2b17a26b2e992a714e8ffa597f49b42004ece08ce8a85bc85286aae2bbcb6702e852bdad4f93187902d

test:
  secret_key_base: a8e0e5298dc473048d2225a060ca3d76c912d11a24b0bac4acfa1f1f449d116fa5161fccc5e2898060e6765a60948759ceb2c1c67db708d98464916403dc7cff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
